# Generated by Django 5.0.1 on 2024-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_text',
            field=models.TextField(default=''),
        ),
    ]
