# Generated by Django 5.0.1 on 2024-02-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_alter_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='captcha',
            field=models.BooleanField(default=False),
        ),
    ]
