# Generated by Django 5.0.1 on 2024-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_user_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
